# This workflow is used to upload and deploy a new release to PyPi
# Based on https://github.com/pypa/gh-action-pypi-publish

name: PyPi Release

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  build:
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      shell: bash -l {0}
      run: |
        pip install setuptools versioneer[toml]==0.29
        python setup.py sdist bdist_wheel
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
