name: Integrationtests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      shell: bash -l {0}
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment-notebooks.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 5
      run: |
        pip install .
        papermill notebooks/lammps.ipynb lammps_out.ipynb -k python3
        papermill notebooks/sphinxdft.ipynb sphinxdft_out.ipynb -k python3
